[{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 87\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.override.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose8819056837313563789 --ansi never kill\r\nCódigo de saída do comando: 1\r\nSaída de comando: \r\nErro de comando: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 87\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.override.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose8819056837313563789 --ansi never kill\r\nCódigo de saída do comando: 1\r\nSaída de comando: \r\nErro de comando: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 87\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.override.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose8819056837313563789 --ansi never kill\r\nCódigo de saída do comando: 1\r\nSaída de comando: \r\nErro de comando: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n"},{"ContainerToolsException.Message":"As Ferramentas do Visual Studio para Contêineres exigem que o Docker esteja em execução antes de compilar, depurar ou executar um projeto em contêiner.  Para obter mais informações, confira: https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 253\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:linha 104\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:linha 418\r\n--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext() na C:\\a\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:linha 87\r\nCódigo de erro: DT1001\r\nGravidade: Error\r\nLinha de comando: docker-compose  -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\docker-compose.override.yml\" -f \"C:\\Users\\MLKjo\\Documents\\workspace\\TrafficTicketControl\\src\\TrafficTicket\\obj\\Docker\\docker-compose.vs.release.partial.g.yml\" -p dockercompose8819056837313563789 --ansi never kill\r\nCódigo de saída do comando: 1\r\nSaída de comando: \r\nErro de comando: Named volume \"portainer_data:/data:rw\" is used in service \"portainer\" but no declaration was found in the volumes section.\r\n"}]